language: go

go:
        - 1.6.x
        - 1.7.x
        - 1.x

install:
        - go get github.com/golang/lint/golint
        - go get golang.org/x/net/context
        - go get golang.org/x/net/context/ctxhttp

script:
        - go test -v ./...
        - go test -cover -race ./...
        - go vet ./...
        - test -z "$(find . -name \*.go | xargs gofmt -d -s)"
        - golint ./...

sudo: false
